### ISSUE TITLE
Sorting imports must considered the renamed symbol 

### ISSUE THREAD

**Issue by mohsen1** [dprint/dprint-plugin-typescript#131]
```ts
import { B, A as C } from 'foo';
```

dprint prints 

```ts
import { A as C, B } from 'foo';
```

prettier prints 

```ts
import { B, A as C } from 'foo';
```

I think prettier is correct. I am using `B` and `C`. `A` is not relevant to me

**Comment by dsherret** [comment]
I don't think prettier sorts imports (I think it leaves it as-is). I think you're correct, but I will think about this one.

**Comment by mohsen1** [comment]
Correction, we're using a [plugin](https://github.com/trivago/prettier-plugin-sort-imports) for sorting imports

**Comment by dsherret** [comment]
Yes, I think you're right that it should be sorted this way because when someone is working in a file they are using the local name rather than the imported name. So when they would go to look at the import/export specifier they would look at the local name.

Does your sorting plugin do the same thing for export specifiers? I wonder if that should sort based on the local name so it would maintain the current behaviour of `export { A as C, B };`... I guess either could work for that and might be good to align with the sorting of import specifiers. I don't have a strong opinion on it.

**Comment by mohsen1** [comment]
This is very subjective and I don't have a strong opinion on it. At first I didn't realize it's not a discrepancy between Prettier and dprint because I missed that I'm using a plugin. 

I don't think configuration options is appropriate either because once you have an option in configs you are introducing something for teams to argue about!

**Comment by dsherret** [comment]
Ok thanks for the feedback! I'm going to close this one and have it align with the TypeScript compiler in this case.

Yeah, the problem with adding sorting config is that it's a very slippery slope to having lots of sorting config.
