### ISSUE TITLE
JSX parenthesization

### ISSUE THREAD

**Issue by devongovett** [dprint/dprint-plugin-typescript#133]
Prettier formats the following example

```jsx
function Example() {
  let [count, setCount] = React.useState(0);
  return <ActionButton onPress={() => setCount((c) => c + 1)}>
    {count} Edits
  </ActionButton>;
}
```

with parenthesis like:

```jsx
function Example() {
  let [count, setCount] = React.useState(0);
  return (
    <ActionButton onPress={() => setCount((c) => c + 1)}>
      {count} Edits
    </ActionButton>
  );
}
```

which I prefer. dprint does not automatically add parentheses, and also if there are parentheses, it does not enforce that the JSX element is indented (i.e. the parens are on the same line as the opening and closing elements). Prettier seems to only do this if the JSX element takes more than one line.

Would this be an acceptable change to make to dprint? Should it be an option? I'm happy to try to contribute this, just wanted to get feedback first.

**Comment by dsherret** [comment]
Thanks for logging this! Yeah, I think maybe `"jsxElement.multiLineParens": true` and it would default to true? The JSX support in dprint has not been great because I haven't done a lot of web programming until recently.

If you would like to work on this then please feel free and go for it! There is an outline of how the IR works here: https://github.com/dprint/dprint/blob/main/docs/overview.md and to see a kind of "debugging output" you can add `(trace)` to a test's description (hopefully that works... just added it recently).

**Comment by lucacasonato** [comment]
Ref https://github.com/denoland/deno/issues/7870 :-)

**Comment by lucacasonato** [comment]
🎉🎉💯 - thanks @dsherret!!
