### ISSUE TITLE
Array access stays on next line after `[` token

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#278]
**Describe the bug**

array access after a `()` expression is interpreted as array definition

dprint-plugin-typescript version: 0.52.1 and 0.51.0

**Input Code**

```ts
(await dprint.outputResolvedConfig({ restrictPlugin: dprintOptions.restrictPlugin }))[
    pluginType]
```

**Expected Output**

```ts
(await dprint.outputResolvedConfig({
    restrictPlugin: dprintOptions.restrictPlugin,
}))[pluginType];
```

**Actual Output**

```ts
(await dprint.outputResolvedConfig({
    restrictPlugin: dprintOptions.restrictPlugin,
}))[
    pluginType
];
```

see https://dprint.dev/playground/#code/BQQw7iCWAuAEAmAHATpAdtAdAewK7UXwCUBTAZ2wBsA3E+AYWzQDNIBzYAb1mXOlQDG0AAqVcbdAC4EKdNADyiaJCZlMvMv0hDR49LAC+ASiMBtAFCwrsRGIloAKgE9EJALpA/language/typescript

**Comment by dsherret** [comment]
This is expected because dprint-plugin-typescript currently respects line breaks after the `[` token for both array expressions and computed expressions (element access expressions):

https://dprint.dev/playground/#code/MYewdgzgLgBLC8cCm0DaAoGWYAcA2ArgOYCWYAKgJ45IC66oksBMiG2uhpF1dQA/language/typescript

It can be resolved by manually moving it back to the previous line.

If you turn on `"computed.preferSingleLine": true` you will see it move to the previous line, but I wouldn't recommend using this yet because it's experimental (expressions are hard and I need to come up with a better way of laying them out nicely). Perhaps it will be on by default in the future.
