### ISSUE TITLE
Documentation request: how to configure to match behaviour of prettier

### ISSUE THREAD

**Issue by snoblenet** [dprint/dprint-plugin-typescript#347]
We use Prettier to check formatting in our CI/CD.

I use Dprint to format more quickly locally.

Could the Dprint documentation please explain how to configure it to match Prettier's behavior?

(Aside from just giving up and using the Prettier plugin for Dprint.)

For example,

Prettier prefers:

```
{
  key: condition ? value1 : value2,
}
```

...even when well under the target line length.

Dprint prefers:

```
{
  key: condition
    ? value1
    : value2,
}
```

Dprint's formatting looks great to me, but fails on CI/CD.

To try to mimic Prettier's behaviour I have tried the following, but it does not work:

```
{
  ...
  "binaryExpression.linePerExpression": false,
  "binaryExpression.operatorPosition": "sameLine",
  "binaryExpression.preferSingleLine": true,
  ...
}
```

**Comment by dsherret** [comment]
> We use Prettier to check formatting in our CI/CD.
>
> I use Dprint to format more quickly locally.

There's no way that dprint-plugin-typescript is going to match prettier. The implementations are very different so even with config it would be very tough for me to match it.

That said, the closest to prettier for dprint-plugin-typescript is probably to use what deno uses. There's a high level `"deno"` config that applies the settings:

```
{
  "deno": true,
  "indentWidth": 4,
  "quoteProps": "asNeeded" // this will become the default in deno's config later
}
```

By the way, that example you gave is just because by default dprint-plugin-typescript respects explicit newlines https://dprint.dev/plugins/typescript/#explicit-newlines -- there is the `"preferSingleLine"`-like config, but it's kind of experimental at this point and I wouldn't recommend using it.

**Comment by dsherret** [comment]
Oh, by the way, if you're only looking for faster formats, if you use the [dprint-plugin-prettier](https://github.com/dprint/dprint-plugin-prettier) locally it should be faster than prettier's cli (especially with incremental formatting enabled). One issue though is the version used in dprint-plugin-prettier might be different than the version used on your CI.

**Comment by snoblenet** [comment]
OK cheers. I might just continue to use Dprint for personal readability while I type and try to remember to run Prettier once manually before each commit.
