### ISSUE TITLE
Question: what is "hanging"?

### ISSUE THREAD

**Issue by heroboy** [dprint/dprint-plugin-typescript#36]
My English is not good. Can you give me example of `bracePosition: "nextLineIfHanging"` and `preferHanging`.

**Comment by dsherret** [comment]
I opened #37 because that configuration option could probably have its name changed.

The `nextLineIfHanging` is only useful when `preferHanging` is `true`. For example, given the following configuration:

```json
{
  "lineWidth": 40,
  "preferHanging": true,
  "bracePosition": "nextLineIfHanging"
}
```

It will format the following:

```ts
if (testingThisOutWithSome && testingTesting) {
    console.log(5);
}
```

Like so:

```ts
if (testingThisOutWithSome
    && testingTesting)
{
    console.log(5);
}
```

This is to visually break up the if statement header from the body, bbecause with the following configuration:

```json
{
  "lineWidth": 40,
  "preferHanging": true,
  "bracePosition": "sameLine"
}
```

It formats like so:

```ts
if (testingThisOutWithSome
    && testingTesting) {
    console.log(5);
}
```

[Playground](https://dprint.dev/playground/#code/JYMwBAFALgpgzlYA7A5gFQBbDgeQK5QDqwUGAygPYC2MYAZHWLAsuvIqgJRgDeAsACgwwsAGMKSOBQA2MAHTSKKCAFZOAbkEBfQYID0esAEM4YCgAdzFODAAmTCmADuGGEjAAiAEYAnI6JgABWsSYAkPAC5POCMaABlkGA9dAQMwW3MfZCgAWmAUJAofGEFQSGYOdCxcAmJSShpBEXpGCtY0dlZufiERcUkZeUVlNU0BLSA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgBYAGAGnCgAcAnRAM0SoAkBDeAcwTbzAyoFdEZCJABGVZgGNEABQD2AZ1gZYs+N0hIAHhgAyCRAElaLdp0ggAviCA/language/typescript)

**Comment by dsherret** [comment]
Note that by defaut with `"preferHanging": false` the "if hanging" doesn't matter.

```json
{
  "lineWidth": 40
}
```

And it formats like so:

```
if (
    testingThisOutWithSome
    && testingTesting
) {
    console.log(5);
}
```

By the way, "hanging" means "hanging indentation"

**Comment by heroboy** [comment]
Thanks.
As I can understand `"preferHanging": true` means when it must split code to multiple lines, I will *not* add a next line before the first item.
