### ISSUE TITLE
Maintain conditional expression branch position, or a add "match" like formatting

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint-plugin-typescript#403]
In the TypeScript project, we often write conditional expressions like this:

```ts
function base64FormatEncode(value) {
    return value < 0 ? fail("Invalid value") :
        value < 26 ? 0x41 /*A*/ + value :
        value < 52 ? 0x61 /*a*/ + value - 26 :
        value < 62 ? 0x30 /*0*/ + value - 52 :
        value === 62 ? 0x2B /*+*/ :
        value === 63 ? 0x2F /*/*/ :
        fail("Invalid value");
}
```

or

```ts
function getApparentType(type: Type): Type {
    const t = !(type.flags & TypeFlags.Instantiable) ? type : getBaseConstraintOfType(type) || unknownType;
    return getObjectFlags(t) & ObjectFlags.Mapped ? getApparentTypeOfMappedType(t as MappedType) :
        t.flags & TypeFlags.Intersection ? getApparentTypeOfIntersectionType(t as IntersectionType) :
        t.flags & TypeFlags.StringLike ? globalStringType :
        t.flags & TypeFlags.NumberLike ? globalNumberType :
        t.flags & TypeFlags.BigIntLike ? getGlobalBigIntType() :
        t.flags & TypeFlags.BooleanLike ? globalBooleanType :
        t.flags & TypeFlags.ESSymbolLike ? getGlobalESSymbolType() :
        t.flags & TypeFlags.NonPrimitive ? emptyObjectType :
        t.flags & TypeFlags.Index ? keyofConstraintType :
        t.flags & TypeFlags.Unknown && !strictNullChecks ? emptyObjectType :
        t;
}
```

Where it's a chain of cases, condition on the left, result on the right.

When I format this with dprint, these are reformatted to split the cases apart (with the operator being positioned according to `conditionalExpression.operatorPosition`):

```ts
function base64FormatEncode(value) {
    return value < 0 ?
        fail("Invalid value") :
        value < 26 ?
        0x41 /*A*/ + value :
        value < 52 ?
        0x61 /*a*/ + value - 26 :
        value < 62 ?
        0x30 /*0*/ + value - 52 :
        value === 62 ?
        0x2B : /*+*/
        value === 63 ?
        0x2F : /*/*/
        fail("Invalid value");
}
```

```ts
function getApparentType(type: Type): Type {
    const t = !(type.flags & TypeFlags.Instantiable) ? type : getBaseConstraintOfType(type) || unknownType;
    return getObjectFlags(t) & ObjectFlags.Mapped ?
        getApparentTypeOfMappedType(t as MappedType) :
        t.flags & TypeFlags.Intersection ?
        getApparentTypeOfIntersectionType(t as IntersectionType) :
        t.flags & TypeFlags.StringLike ?
        globalStringType :
        t.flags & TypeFlags.NumberLike ?
        globalNumberType :
        t.flags & TypeFlags.BigIntLike ?
        getGlobalBigIntType() :
        t.flags & TypeFlags.BooleanLike ?
        globalBooleanType :
        t.flags & TypeFlags.ESSymbolLike ?
        getGlobalESSymbolType() :
        t.flags & TypeFlags.NonPrimitive ?
        emptyObjectType :
        t.flags & TypeFlags.Index ?
        keyofConstraintType :
        t.flags & TypeFlags.Unknown && !strictNullChecks ?
        emptyObjectType :
        t;
}
```

Is there any way that these conditional expressions could be maintained?

Adding a special mode that would explicitly format conditionals like this may also work, but I can't say that all of our examples of this are formatted like this (but a lot are, especially in the checker).

**Comment by dsherret** [comment]
Huh, I'm surprised this never came up before because the way you're formatting it is much easier to read. I guess dprint is just copying prettier.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEARgIYDOcAbACwBiEATgLbEwCiWEAJnABQBuxADbo4ASnzAAOlHyz89ODHT0ZA4XHwAefAAZ8AfnypiOQT0kgAklDU5O+NSIvik0ue4dCRW-ACYKBroAHlQAjPgA9ABUAIJREfgA1J7q+K4yHrKOGtoArL6BOkEU4dHE8Ukp3gC0fgHpmVleOfgUBYZFAMx60ToVydn4tflpbo2DALxTre3BvgBCkVGJFQ3jzfhTE62dhUG+NEvRCWuZxqbmVjZCdlVwzgDc0gC+IAA0IBAADrjQpMigYj0egQADuAAUgQh-ighKDiABPf4fQj0YhgADWigAysRGHAADI4KBwZDGQTkFFozE4r7o4kAc2QMHoIg+cEYhDgnG4nAJxCgDPQxAZcDoTBYuEFyBAxHQMAg7xAAAsYIxBAB1ZU4eCkOlgODY6E6nB8HUImVgUjIkDE8j0GDgtEM5hkoSUkAAK1IQWxjMEcAAiugIPA3RS4B86fR7TKSFzBEqvvRiTANXYYMrkAAOHRRkHkDVor4y5Nwe18UkfACOIfgTu+MNlpGqJO53KVClrOAUTpFrqQ5I95EYOGZrMjIFI-qDddJg-dk5gxEI6c4meQvg+LJMgkZAGEIIwByBy7klehyAAVFcwoeTvgiazcWDYsApn4xKCcbEwBEB8NyGeZ4gA

I kind of want it to format the way you mentioned by default. Will think about this.

**Comment by jakebailey** [comment]
I think at least having the option to maintain things is what I'm looking for; IMO this isn't always the best method, but in some circumstances where it's basically a big match/case it sort of works fine. I'm not too picky, personally, but some people are, so I'm trying to make dprint look at least a little like our typical coding style. (There are some other issues I'm probably going to report as I review a huge diff on the TS project...)

**Comment by jakebailey** [comment]
Is the behavior flipped? Shouldn't `conditionalExpression.linePerExpression: true` enable this? I just tried it on TS now that it's merged, and had to set `false` like the test does, which seems backwards from your statement that you'd want it to be the default.

**Comment by jakebailey** [comment]
Oh, I guess `line per expression` meaning each individual one gets its own line, as opposed to `false`, where the condition expression and its value expression are on the same line. I guess false is "maintain"?

**Comment by dsherret** [comment]
Yeah, `false` is maintain. `linePerExpression` means that when it goes to multiple lines it will make each sub expression of the conditional expression go on a new line. I used that because there is `binaryExpression.linePerExpression` and `memberExpression.linePerExpression` at the moment. I think probably ideally in the future some of these boolean configurations would be merged to a single config. I just couldn't think of anything atm.
