### ISSUE TITLE
Formatting error after return

### ISSUE THREAD

**Issue by doox911** [dprint/dprint-plugin-typescript#446]
**Describe the bug**

dprint-plugin-typescript version: 0.76.0

**Input Code**

```ts
export const test = () => {
    return 
    1;
}
```

**Expected Output**

```ts
export const test = () => {
    return 1;
}
```

**Actual Output**

```ts
export const test = () => {
  return;
  1;
};
```

**Comment by dsherret** [comment]
This is expected because of implicit returns in JavaScript.

![image](https://user-images.githubusercontent.com/1609021/198303573-7232ac21-89b1-433e-a15d-9d86fb529dc5.png)

If you run `test()` in the original code, it will return `undefined` and so the actual output keeps that behaviour rather than modifying it.

**Comment by doox911** [comment]
> This is expected because of implicit returns in JavaScript. The two lines are separate statements so dprint-plugin-typescript only ensures there's a semi-colon on the end of each one.
> 
> ![image](https://user-images.githubusercontent.com/1609021/198303573-7232ac21-89b1-433e-a15d-9d86fb529dc5.png)
> 
> If you run `test()` in the original code, it will return `undefined` and so the actual output keeps that behaviour rather than modifying it.

Okay)
