### ISSUE TITLE
Inserted `{" "}`

### ISSUE THREAD

**Issue by vwkd** [dprint/dprint-plugin-typescript#500]
**Describe the bug**

dprint-plugin-typescript version: 0.83.0

https://dprint.dev/playground/#code/GYVwdgxgLglg9mABMOcAUBKRBvAUIxAJwFMoRCk18CaAeAExgDcA+amux19jz5t3oOSoAXDgCGk8QDoARvIXzpEFarUBfRAHoJUuYoXT6xk6bMnEAH0uIARLPGFb6noNpauAoe8+vEP-moMAG5cdSA/language/typescript

**Input Code**

```ts
function foo() {
  return (
      <div>
        <div>
          <div>
            foo: {aaaa.bbbbbbbb.cccccccccc} / {aaaa.bbbbbbbb.dddddddddddddddddd || "bar"}
          </div>
        </div>
      </div>
  );
}
```

**Expected Output**

```ts
function foo() {
  return (
    <div>
      <div>
        <div>
          foo: {aaaa.bbbbbbbb.cccccccccc} / {aaaa.bbbbbbbb.dddddddddddddddddd || "bar"}
        </div>
      </div>
    </div>
  );
}
```

**Actual Output**

```ts
function foo() {
  return (
    <div>
      <div>
        <div>
          foo: {aaaa.bbbbbbbb.cccccccccc} /{" "}
          {aaaa.bbbbbbbb.dddddddddddddddddd || "bar"}
        </div>
      </div>
    </div>
  );
}
```

**Comment by dsherret** [comment]
That's working as intended to align with Prettier:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++ATnDOvbSTXZ-gDwAmOANwB8HLpz6CRtMVwnDRMrkQhJKAQw1qAdACM9+vVrDGTpgL74A9Os26D+rbyfOXr5-gA+H-FRA619L5mCorclvzy0jJhEVLR4ZKiZADcNGYgADQgEAAOuNAAzsigAfQQAO4ACgEIRShqADblagCeRVk69GpgANZMAMpqALZwADI4UHDIqI0FcB1dvQM53RMA5sgw9OjzIHBDOnBOR6NqUGvoamtwAGIQ9ENqMLjnyCBq6DAQmSAAFjBDBoAdV+OHgBRWYDg-VqYMEYJabzABXaIAmc3oMEqXTWj2ms12ACsCgAPfrrBpwACK6Ag8HxDTmWRW9Axb38hwaPxy9AmMCBOF4MF+yAAHAAGZllOZAro5N48uAYgRTLIAR1p8GxuTq7wKAFpJkcjj9GBqcIxsVc8UgZozdnMhjhNtsHRS4ABBZ68nSfOCVOD0caTBlMkAFd00ulTW0ErIwNQ6AVCkVIABM8a6OAa6wAwhAhja9gUAKw-dBzAAqibqdrDAh2AEkoLwEDB+mBeXkPS3+jAWpTQ3AzGYgA

It's because when going from one line to two it needs to maintain the space in JSX.
