### ISSUE TITLE
Parse error when encountering JSDoc style types in declaration files

### ISSUE THREAD

**Issue by Gerrit0** [dprint/dprint-plugin-typescript#593]
**Describe the bug**

dprint-plugin-typescript version: 0.88.7

dprint can't handle declaration files which contain unusual types that aren't valid in normal TS files.
I wish TS didn't allow this, but it does, so I have a testcase for it in TypeDoc... and dprint doesn't like it.

**Input Code**

```ts
// skipNullChecks.d.ts
export function nullable(opt: ?string): void;
export function nonNullable(opt: !string): void;
```

**Expected Output**

```ts
// skipNullChecks.d.ts
export function nullable(opt: ?string): void;
export function nonNullable(opt: !string): void;
```

**Actual Output**

Error:

```
Error formatting /home/gerrit/Desktop/typedoc_master/src/test/converter2/issues/gh1524.d.ts. Message: Unexpected token `?`. Expected an identifier, void, yield, null, await, break, a string literal, a numeric literal, true, false, `, -, import, this, typeof, {, [, ( at /home/gerrit/Desktop/typedoc_master/src/test/converter2/issues/gh1524.d.ts:1:31

  export function nullable(opt: ?string): void;
                                ~
Had 1 error formatting.
```

**Comment by dsherret** [comment]
Does TS actually allow it? I get errors for both:

![image](https://github.com/dprint/dprint-plugin-typescript/assets/1609021/f5802bb6-ce1f-4dce-b920-a1d14a7c6a54)

**Comment by Gerrit0** [comment]
It does -- if and only if `skipLibCheck` is turned on, sorry, I could have sworn I included that in the original issue!

![image](https://github.com/dprint/dprint-plugin-typescript/assets/19329837/a2bd8c44-6802-4f32-91d5-bfdadedb2160)

**Comment by dsherret** [comment]
In this case, the diagnostic is suppressed because TypeScript does it's best to parse the file and then doesn't surface these errors because of `skipLibCheck` being off. I'm going to categorize this one as "wont fix" because it's not valid TypeScript code.

In this case, people should manually change their code from `opt: ?string` to the equivalent `opt: string | null`. That will also make the TypeScript code work in cases where people don't have `skipLibCheck` enabled.

In your case of having it as a test file, I recommend adding a `// dprint-ignore-file` statement at the top of the file, or exclude it in the dprint.json config.
