### ISSUE TITLE
eslint sort-import vs dprint sort imports

### ISSUE THREAD

**Issue by mohamedmansour** [dprint/dprint-plugin-typescript#595]
I am using version `0.44.0` and eslint sort-import config:

```
    "sort-imports": [
      "error",
      {
        "ignoreDeclarationSort": true,
        "allowSeparatedGroups": true
      }
    ],
```

Does this sort:
```
import { StubResizeObserver, fetchHTML, stubResizeObserver } from '../../test_utils/test-helper.js';
```

Meanwhile dprint does:
```
import { fetchHTML, StubResizeObserver, stubResizeObserver } from '../../test_utils/test-helper.js';
```

I tried using dprint config like:
```
  "typescript": {
    "lineWidth": 120,
    "quoteStyle": "preferSingle",
    "binaryExpression.operatorPosition": "sameLine",
    "typeLiteral.separatorKind": "comma",
    "module.sortImportDeclarations": "caseSensitive",
    "module.sortExportDeclarations": "caseSensitive"
  },
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.88.7.wasm"
  ]
```
But it always does a case insensitive sort. I am trying to match eslint and dprint together to make the DX nicer, any recommendations?

**Comment by dsherret** [comment]
Use:

```json
{
  "exportDeclaration.sortNamedExports": "caseSensitive",
  "importDeclaration.sortNamedImports": "caseSensitive"
}
```

Then you can remove the eslint rule as it's no longer necessary because the formatter handles it for you now.

Side note: `module.sortImportDeclarations` is for sorting individual import declarations in a module rather than the named imports within an import declaration.

https://dprint.dev/playground/#code/JYWwDg9gTgLgBAbzgZRgVwEYCUCmBnYALxwHkM8coA3SgGjgDMcYBjACwAkAVAWQBl6edNnxFS5SjShwAvoygQQcAOQA6VQHp1GmPhgB9NDGAAbPDr0BaNjhNhKqgFZ5lAbiA/config/N4WAUABBBECmAeAHA9gJwC4BFYGMA2AhqgegJbIB2AdAM5roByBAtrACYCiS9N0AXDBwEasAMqwKNUmQBusaABpwUaKWYoM2fERLlqdDE1ZsAkup79BwsRKmz54AL7ggA/plugin/typescript

**Comment by mohamedmansour** [comment]
That worked, thank you! I didn't see this Config page at first! Thank you https://dprint.dev/plugins/typescript/config/

**Comment by adrian-gierakowski** [comment]
For what it’s worth, when I first discovered dprint, I struggled to find individual plugin config docs as well. So maybe something could  be improved about the website

**Comment by glwbr** [comment]
Hey, I just bumped in a similar issue, I configured dprint, but it's not enforcing the order for types, am I missing something in here?
![image](https://github.com/user-attachments/assets/1c100185-6f6c-4d69-9434-4e37e6a529cd)
