### ISSUE TITLE
Missing space for `export default function doX()` with `spaceBeforeParentheses`

### ISSUE THREAD

**Issue by ad-si** [dprint/dprint-plugin-typescript#642]
**Describe the bug**

Missing space after the function name when using `spaceBeforeParentheses` for `export default function doX()` statement.

https://dprint.dev/playground/#code/GYVwdgxgLglg9mABAgpgCgJSIN4ChEGIBOKUIRSAjLgL664oAeADnEVIqJLAolAO5xMOfIRJkKiAEy16TVu0QATFMACGIADYcu0eEigALEuix5CxUuSQBmWkA/config/N4KABGBEBmCuB2BjALgSwPbwCIFNEBsBDAJ0LUwDoBnAB0MRwCEdp1icAFEneZACxxVBkAFxhkxWDhABfEEA/plugin/typescript

**Input Code**

```ts
export default function three() {
    return 3
}
```

**Expected Output**

```ts
export default function three () {
    return 3
}
```

**Actual Output**

```ts
export default function three() {
    return 3
}
```

**Comment by todor-a** [comment]
The problem is actually with `swc` and the fact that it reports the exported default function declaration as a function expression. Opened an [issue](https://github.com/swc-project/swc/issues/9120).

**Comment by dsherret** [comment]
This is expected because that's controlled via `"functionExpression.spaceBeforeParentheses": true`. It's a function expression and not declaration at `export default ...` (not a bug in swc). It's why you can do `export default function() {}` without a name.

That said, for formatting concerns, this is often considered to be like a declaration and so maybe this option should change the behaviour of that too.

**Comment by dsherret** [comment]
Oh wait, you might be right. I'll look into it more after I finish eating.

**Comment by dsherret** [comment]
Yeah, this should be treated as a function declaration https://262.ecma-international.org/14.0/#prod-ExportDeclaration
