### ISSUE TITLE
Remove semicolon on export declarations

### ISSUE THREAD

**Issue by guybedford** [dprint/dprint-plugin-typescript#73]
A named export declaration like:

```js
export {
 name
}
```

is a declaration ending in a brace so strictly shouldn't need a semicolon.

It is optional so granted this is completely subjective, but has it been discussed removing this to match other declaration forms?

**Comment by dsherret** [comment]
Hmmm... I used to have ast node specific semi-colon level configuration, but not anymore 😅

I'm not sure, as prettier also adds a semi-colon here and I don't see any discussion in its repo about it.

FWIW, the escmascript spec has a semi-colon after named exports on an export declaration, but then it also has a semi-colon on class & function `export default` declarations so can't really decide based on that.

Thinking about it more, I think the reason a semi-colon is added here is because an export declaration with named exports is more "statement-like" than "declaration-like". `export default class MyClass {}` is what I would consider "declaration-like" and `export { name }` is something I would consider "statement-like" even though it is a technically a declaration. This is similar to import declarations having a semi-colon, but I know those don't end in braces. In other words, "statement-like" with a semi-colon is kind of forwarding or redirecting names, while "declaration-like" is declaring the source. Does that make sense? I'm not sure it's a valid point or reason to have a semi-colon here, but I think probably the semantics of the line are more important than it ending in a close brace.

**Comment by guybedford** [comment]
The reason why it feels declaration-like to me is that the bindings are static, so the order the statement comes in in the source text doesn't matter at all.

By this logic though, strictly speaking import declarations are the same and shouldn't have semicolons either really!

We really should have defined the syntax to put the string specifiers first:

```js
import from 'mod' {
  name
}
```

to get better editor hints and then both forms could have been without a trailing `;` and there would be no need for the distinctions between the forms. Only `export const...` `export default expression;` would be the semicolon cases then which have expressions that have source ordering that matters and are the only forms like that.

I guess one big difference as well is that:

```js
export function p () {
};
```

parses as a named declaration followed by an empty statement, while:

```js
export { p };
```

does just parse as a declaration and I suppose this mirrors an import declaration as well for the most part.

I guess this is the common pattern though, so probably best not to fight it but yeah naively I would have expected the general rule to be "no semicolon for declarations ending in a brace" where import statements are the exception due to their string ending being more of an aesthetic thing.

Will close, but interesting to consider indeed!

**Comment by dsherret** [comment]
@guybedford good points!

Yeah, I think given the arbitrariness-ish of this, probably the strongest argument here for keeping it as-is is just "prettier does it this way" and this formatter is kind of piggy backing off the precedent it set (though I am all for breaking precedents!), so I'll keep it aligned to prettier, but if they change in the future then I'll align.
